services:
  web:
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "80:5000"
    container_name: web-container
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      REDIS_HOST: redis  
      MYSQL_HOST: db  
      MYSQL_USER: user
      MYSQL_PASSWORD: password  
      MYSQL_DATABASE: mydatabase  

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data  

  mysql: 
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user  
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  tester:
    build:
      context: .  
      dockerfile: Dockerfile.test  
    volumes:
      - .:/app
    depends_on:
      - web  

volumes:
  redis-data:
  mysql-data: