services:
  app:
    build:  
      context: .  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py

  tester:
    build:
      context: .  
      dockerfile: Dockerfile.test  
    volumes:
      - .:/app
    depends_on:
      - app  
