name: Deploy to HTTP Servers via Bastion

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE: gearvian/capestone
  TAG: ${{ github.sha }}       
  HTTP_SERVERS: |
    10.0.2.215
    10.0.2.214
  BASTION_IP: 8.213.39.96 
  SSH_USER: root
  CONTAINER_NAME: web-container

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1.2 SSH into Bastion with agent forwarding to deploy on HTTP servers
    - name: Deploy to HTTP Servers via Bastion
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ env.BASTION_IP }}  # Bastion server's public IP
        key: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}  # SSH key for bastion, stored in GitHub secrets
        user: ${{ env.SSH_USER }}  # SSH user for bastion
        use-ssh-agent: true  # Enable SSH agent forwarding
        script: |
          echo "Deploying to servers behind bastion"
          for server in ${{ env.HTTP_SERVERS }}; do
            echo "Connecting to $server via bastion using SSH agent forwarding..."
            ssh -o StrictHostKeyChecking=no $SSH_USER@$server "
              docker pull $REGISTRY/$IMAGE:$TAG &&
              docker stop $CONTAINER_NAME || true &&
              docker rm $CONTAINER_NAME || true &&
              docker run -d --name $CONTAINER_NAME -p 5000:5000 $REGISTRY/$IMAGE:$TAG
            "
          done
