on:
  push:
    branches:
      - main  

env:
  SSH_KEY: ${{ secrets.BASTION_SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.SSH_USERNAME }}
  SSH_HOST1: ${{ secrets.Server1 }}
  SSH_HOST2: ${{ secrets.Server2 }}

jobs:
  deploy1:
    runs-on: self-hosted
    steps:
      - name: Deploying to server 1
        run: |
          echo "${{ secrets.BASTION_SSH_PRIVATE_KEY }}" > capstone-key.pem
          chmod 600 capstone-key.pem
          ssh -i capstone-key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.Server1 }} << 'EOF'
            cd ..
            cd Capestone/
            git pull https://github.com/Gearvian/Capestone.git
            docker compose down
            docker compose up -d 
          EOF

  deploy2:
    runs-on: self-hosted
    steps:
      - name: Deploying to server 2
        run: |
          echo "${{ secrets.BASTION_SSH_PRIVATE_KEY }}" > capstone-key.pem
          chmod 600 capstone-key.pem
          ssh -i capstone-key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.Server2 }} << 'EOF'
            cd ..
            cd Capestone/
            git pull https://github.com/Gearvian/Capestone.git
            docker compose down
            docker compose up -d 
          EOF