name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: 
          - server1.example.com
          - server2.example.com

    steps:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3
          
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker Image
        run: |
          echo "Pulling Docker image..."
          docker pull gearvian/capestone:latest

      - name: Deploy to Server
        env:
          SERVER: ${{ matrix.server }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this is set in your repo secrets
        run: |
          echo "Deploying to $SERVER..."
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh -o StrictHostKeyChecking=no -i /dev/stdin user@$SERVER "docker stop my-container || true && docker rm my-container || true && docker run -d --name my-container yourusername/your-image:latest"